import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
import Global_Variables as GV

def send_email(sender_email, sender_password, recipient_email, subject, body):
    # Set up the SMTP server
    smtp_server = "smtp.gmail.com"
    smtp_port = 587

    # Create the email
    msg = MIMEMultipart()
    msg['From'] = sender_email
    msg['To'] = recipient_email
    msg['Subject'] = subject

    # Attach the email body
    msg.attach(MIMEText(body, 'plain'))

    try:
        # Connect to the SMTP server and start TLS for security
        server = smtplib.SMTP(smtp_server, smtp_port)
        server.starttls()

        # Log in to the server
        server.login(sender_email, sender_password)

        # Send the email
        server.send_message(msg)

        # Close the connection
        server.quit()

        print(f"Client Email sent successfully! {recipient_email}")

    except Exception as e:
        print(f"Failed to send client email: {e}")

# Example usage


def Mail_Sending_Client(email_id, domain, description):
    subject_for_mail = f"Lemolite: Confirmation mail for {domain} project" 
    body = f"""
Your request for the project,

Domain: {domain},
Description: {description}.

has been register to our portal, our sales executive will contact you shortly.

This is an autogenerated mail if any query related to this mail please don't reply, 
if you are having any querry then please let us know at connect@lemolite.com

Thank You,
LemoBot,
Lemolite Technologies LLP
            """

    send_email(GV.sender_email, GV.sender_password, email_id, subject_for_mail, body)
